### ISSUE TITLE
Why use HMR?

### ISSUE THREAD

**Issue by LawJolla** [juliancwirko/horizon-react-webpack-boilerplate#1]
Nice project! I'll be picking through it and learning. Lovli.js is bloated. I like your set up. 

Quick question. I have a similar set up using Webpack Dev Server and setting the --hot flag at start. That gives me full hot module reload. 

But I see every other package, including yours, uses React HMR. I don't understand what advantage that gives in addition to Webpack. Can you help explain? Thanks!

**Comment by juliancwirko** [comment]
Hi, you mean `react-hot-loader` right? Webpack will reload your modules, and react-hot-loader is a tool which will keep react components mounted and preserve the states in React app.

**Comment by LawJolla** [comment]
Thanks for the reply!

Can you give me an example of the benefit?  I've read the react-hot-loader docs.  I see how it works as a stand alone, but I don't get it with Webpack Dev.

For instance, with Webpack Dev, if I open a modal `this.state = { isModalOpen: true}` and save changes to the modal component, or any other component, Webpack Dev hot reloads that module and modal remains open, .e.g isModalOpen still equals true.  

It kept "react components mounted and preserved the state."

**Comment by juliancwirko** [comment]
I think this whole article could be useful for you: https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#db27
